DROP TABLE ss_status;
DROP TABLE ss_signup;

CREATE TABLE ss_signup (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    hits INT NOT NULL DEFAULT 0,
    hash VARCHAR(128) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

CREATE TABLE ss_status (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ip VARCHAR(128) NOT NULL,
    port INT NOT NULL,
    hits INT NOT NULL DEFAULT 0,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    signup_id INT NOT NULL,
    INDEX sign_id (signup_id),
    FOREIGN KEY (signup_id) REFERENCES ss_signup(id) ON DELETE CASCADE
) ENGINE=INNODB;
