<?php

define('SERVER_HOST', 'http://localhost');
define('DB_HOSTNAME', 'localhost');
define('DB_USERNAME', 'root');
define('DB_PASSWORD', '');
define('DB_DATABASE', 'db');
define('DB_TABLE_PREFIX', 'ss_');
define('DB_TABLE_SIGNUP', DB_TABLE_PREFIX . 'signup');
define('DB_TABLE_STATUS', DB_TABLE_PREFIX . 'status');

define('GMAIL_USERNAME', 'user@gmail.com');
define('GMAIL_PASSWORD', 'password');
